// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	MessageOutbox       *messageOutbox
	MqDeadLetterMessage *mqDeadLetterMessage
	PayInfo             *payInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	MessageOutbox = &Q.MessageOutbox
	MqDeadLetterMessage = &Q.MqDeadLetterMessage
	PayInfo = &Q.PayInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		MessageOutbox:       newMessageOutbox(db, opts...),
		MqDeadLetterMessage: newMqDeadLetterMessage(db, opts...),
		PayInfo:             newPayInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	MessageOutbox       messageOutbox
	MqDeadLetterMessage mqDeadLetterMessage
	PayInfo             payInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		MessageOutbox:       q.MessageOutbox.clone(db),
		MqDeadLetterMessage: q.MqDeadLetterMessage.clone(db),
		PayInfo:             q.PayInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		MessageOutbox:       q.MessageOutbox.replaceDB(db),
		MqDeadLetterMessage: q.MqDeadLetterMessage.replaceDB(db),
		PayInfo:             q.PayInfo.replaceDB(db),
	}
}

type queryCtx struct {
	MessageOutbox       IMessageOutboxDo
	MqDeadLetterMessage IMqDeadLetterMessageDo
	PayInfo             IPayInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		MessageOutbox:       q.MessageOutbox.WithContext(ctx),
		MqDeadLetterMessage: q.MqDeadLetterMessage.WithContext(ctx),
		PayInfo:             q.PayInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
