// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"seckill-service/internal/data/pay/model"
)

func newMessageOutbox(db *gorm.DB, opts ...gen.DOOption) messageOutbox {
	_messageOutbox := messageOutbox{}

	_messageOutbox.messageOutboxDo.UseDB(db, opts...)
	_messageOutbox.messageOutboxDo.UseModel(&model.MessageOutbox{})

	tableName := _messageOutbox.messageOutboxDo.TableName()
	_messageOutbox.ALL = field.NewAsterisk(tableName)
	_messageOutbox.ID = field.NewUint64(tableName, "id")
	_messageOutbox.EventID = field.NewString(tableName, "event_id")
	_messageOutbox.AggregateType = field.NewString(tableName, "aggregate_type")
	_messageOutbox.AggregateID = field.NewString(tableName, "aggregate_id")
	_messageOutbox.Topic = field.NewString(tableName, "topic")
	_messageOutbox.Payload = field.NewString(tableName, "payload")
	_messageOutbox.Status = field.NewInt32(tableName, "status")
	_messageOutbox.RetryCount = field.NewInt32(tableName, "retry_count")
	_messageOutbox.NextRetryAt = field.NewTime(tableName, "next_retry_at")
	_messageOutbox.CreatedAt = field.NewTime(tableName, "created_at")
	_messageOutbox.UpdatedAt = field.NewTime(tableName, "updated_at")

	_messageOutbox.fillFieldMap()

	return _messageOutbox
}

// messageOutbox 本地消息表
type messageOutbox struct {
	messageOutboxDo messageOutboxDo

	ALL           field.Asterisk
	ID            field.Uint64 // 主键ID
	EventID       field.String // 事件唯一ID
	AggregateType field.String // 聚合根类型（Order/User等）
	AggregateID   field.String // 聚合根ID（订单号/用户ID等）
	Topic         field.String // Kafka Topic
	Payload       field.String // 事件负载（JSON格式）
	Status        field.Int32  // 状态：0-待发送，1-已发送，2-发送失败
	RetryCount    field.Int32  // 已重试次数
	NextRetryAt   field.Time   // 下次重试时间（指数退避）
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m messageOutbox) Table(newTableName string) *messageOutbox {
	m.messageOutboxDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m messageOutbox) As(alias string) *messageOutbox {
	m.messageOutboxDo.DO = *(m.messageOutboxDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *messageOutbox) updateTableName(table string) *messageOutbox {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.EventID = field.NewString(table, "event_id")
	m.AggregateType = field.NewString(table, "aggregate_type")
	m.AggregateID = field.NewString(table, "aggregate_id")
	m.Topic = field.NewString(table, "topic")
	m.Payload = field.NewString(table, "payload")
	m.Status = field.NewInt32(table, "status")
	m.RetryCount = field.NewInt32(table, "retry_count")
	m.NextRetryAt = field.NewTime(table, "next_retry_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *messageOutbox) WithContext(ctx context.Context) IMessageOutboxDo {
	return m.messageOutboxDo.WithContext(ctx)
}

func (m messageOutbox) TableName() string { return m.messageOutboxDo.TableName() }

func (m messageOutbox) Alias() string { return m.messageOutboxDo.Alias() }

func (m messageOutbox) Columns(cols ...field.Expr) gen.Columns {
	return m.messageOutboxDo.Columns(cols...)
}

func (m *messageOutbox) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *messageOutbox) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["event_id"] = m.EventID
	m.fieldMap["aggregate_type"] = m.AggregateType
	m.fieldMap["aggregate_id"] = m.AggregateID
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["payload"] = m.Payload
	m.fieldMap["status"] = m.Status
	m.fieldMap["retry_count"] = m.RetryCount
	m.fieldMap["next_retry_at"] = m.NextRetryAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m messageOutbox) clone(db *gorm.DB) messageOutbox {
	m.messageOutboxDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m messageOutbox) replaceDB(db *gorm.DB) messageOutbox {
	m.messageOutboxDo.ReplaceDB(db)
	return m
}

type messageOutboxDo struct{ gen.DO }

type IMessageOutboxDo interface {
	gen.SubQuery
	Debug() IMessageOutboxDo
	WithContext(ctx context.Context) IMessageOutboxDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMessageOutboxDo
	WriteDB() IMessageOutboxDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMessageOutboxDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMessageOutboxDo
	Not(conds ...gen.Condition) IMessageOutboxDo
	Or(conds ...gen.Condition) IMessageOutboxDo
	Select(conds ...field.Expr) IMessageOutboxDo
	Where(conds ...gen.Condition) IMessageOutboxDo
	Order(conds ...field.Expr) IMessageOutboxDo
	Distinct(cols ...field.Expr) IMessageOutboxDo
	Omit(cols ...field.Expr) IMessageOutboxDo
	Join(table schema.Tabler, on ...field.Expr) IMessageOutboxDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMessageOutboxDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMessageOutboxDo
	Group(cols ...field.Expr) IMessageOutboxDo
	Having(conds ...gen.Condition) IMessageOutboxDo
	Limit(limit int) IMessageOutboxDo
	Offset(offset int) IMessageOutboxDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageOutboxDo
	Unscoped() IMessageOutboxDo
	Create(values ...*model.MessageOutbox) error
	CreateInBatches(values []*model.MessageOutbox, batchSize int) error
	Save(values ...*model.MessageOutbox) error
	First() (*model.MessageOutbox, error)
	Take() (*model.MessageOutbox, error)
	Last() (*model.MessageOutbox, error)
	Find() ([]*model.MessageOutbox, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessageOutbox, err error)
	FindInBatches(result *[]*model.MessageOutbox, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MessageOutbox) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMessageOutboxDo
	Assign(attrs ...field.AssignExpr) IMessageOutboxDo
	Joins(fields ...field.RelationField) IMessageOutboxDo
	Preload(fields ...field.RelationField) IMessageOutboxDo
	FirstOrInit() (*model.MessageOutbox, error)
	FirstOrCreate() (*model.MessageOutbox, error)
	FindByPage(offset int, limit int) (result []*model.MessageOutbox, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMessageOutboxDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m messageOutboxDo) Debug() IMessageOutboxDo {
	return m.withDO(m.DO.Debug())
}

func (m messageOutboxDo) WithContext(ctx context.Context) IMessageOutboxDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m messageOutboxDo) ReadDB() IMessageOutboxDo {
	return m.Clauses(dbresolver.Read)
}

func (m messageOutboxDo) WriteDB() IMessageOutboxDo {
	return m.Clauses(dbresolver.Write)
}

func (m messageOutboxDo) Session(config *gorm.Session) IMessageOutboxDo {
	return m.withDO(m.DO.Session(config))
}

func (m messageOutboxDo) Clauses(conds ...clause.Expression) IMessageOutboxDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m messageOutboxDo) Returning(value interface{}, columns ...string) IMessageOutboxDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m messageOutboxDo) Not(conds ...gen.Condition) IMessageOutboxDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m messageOutboxDo) Or(conds ...gen.Condition) IMessageOutboxDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m messageOutboxDo) Select(conds ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m messageOutboxDo) Where(conds ...gen.Condition) IMessageOutboxDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m messageOutboxDo) Order(conds ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m messageOutboxDo) Distinct(cols ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m messageOutboxDo) Omit(cols ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m messageOutboxDo) Join(table schema.Tabler, on ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m messageOutboxDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m messageOutboxDo) RightJoin(table schema.Tabler, on ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m messageOutboxDo) Group(cols ...field.Expr) IMessageOutboxDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m messageOutboxDo) Having(conds ...gen.Condition) IMessageOutboxDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m messageOutboxDo) Limit(limit int) IMessageOutboxDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m messageOutboxDo) Offset(offset int) IMessageOutboxDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m messageOutboxDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageOutboxDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m messageOutboxDo) Unscoped() IMessageOutboxDo {
	return m.withDO(m.DO.Unscoped())
}

func (m messageOutboxDo) Create(values ...*model.MessageOutbox) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m messageOutboxDo) CreateInBatches(values []*model.MessageOutbox, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m messageOutboxDo) Save(values ...*model.MessageOutbox) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m messageOutboxDo) First() (*model.MessageOutbox, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageOutbox), nil
	}
}

func (m messageOutboxDo) Take() (*model.MessageOutbox, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageOutbox), nil
	}
}

func (m messageOutboxDo) Last() (*model.MessageOutbox, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageOutbox), nil
	}
}

func (m messageOutboxDo) Find() ([]*model.MessageOutbox, error) {
	result, err := m.DO.Find()
	return result.([]*model.MessageOutbox), err
}

func (m messageOutboxDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessageOutbox, err error) {
	buf := make([]*model.MessageOutbox, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m messageOutboxDo) FindInBatches(result *[]*model.MessageOutbox, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m messageOutboxDo) Attrs(attrs ...field.AssignExpr) IMessageOutboxDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m messageOutboxDo) Assign(attrs ...field.AssignExpr) IMessageOutboxDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m messageOutboxDo) Joins(fields ...field.RelationField) IMessageOutboxDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m messageOutboxDo) Preload(fields ...field.RelationField) IMessageOutboxDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m messageOutboxDo) FirstOrInit() (*model.MessageOutbox, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageOutbox), nil
	}
}

func (m messageOutboxDo) FirstOrCreate() (*model.MessageOutbox, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageOutbox), nil
	}
}

func (m messageOutboxDo) FindByPage(offset int, limit int) (result []*model.MessageOutbox, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m messageOutboxDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m messageOutboxDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m messageOutboxDo) Delete(models ...*model.MessageOutbox) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *messageOutboxDo) withDO(do gen.Dao) *messageOutboxDo {
	m.DO = *do.(*gen.DO)
	return m
}
