// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"seckill-service/internal/data/pay/model"
)

func newMqDeadLetterMessage(db *gorm.DB, opts ...gen.DOOption) mqDeadLetterMessage {
	_mqDeadLetterMessage := mqDeadLetterMessage{}

	_mqDeadLetterMessage.mqDeadLetterMessageDo.UseDB(db, opts...)
	_mqDeadLetterMessage.mqDeadLetterMessageDo.UseModel(&model.MqDeadLetterMessage{})

	tableName := _mqDeadLetterMessage.mqDeadLetterMessageDo.TableName()
	_mqDeadLetterMessage.ALL = field.NewAsterisk(tableName)
	_mqDeadLetterMessage.ID = field.NewUint64(tableName, "id")
	_mqDeadLetterMessage.EventID = field.NewString(tableName, "event_id")
	_mqDeadLetterMessage.Topic = field.NewString(tableName, "topic")
	_mqDeadLetterMessage.PartitionID = field.NewInt32(tableName, "partition_id")
	_mqDeadLetterMessage.OffsetID = field.NewInt64(tableName, "offset_id")
	_mqDeadLetterMessage.OrderNo = field.NewString(tableName, "order_no")
	_mqDeadLetterMessage.RequestID = field.NewString(tableName, "request_id")
	_mqDeadLetterMessage.TraceID = field.NewString(tableName, "trace_id")
	_mqDeadLetterMessage.RetryCount = field.NewInt32(tableName, "retry_count")
	_mqDeadLetterMessage.ErrorMessage = field.NewString(tableName, "error_message")
	_mqDeadLetterMessage.RawPayload = field.NewString(tableName, "raw_payload")
	_mqDeadLetterMessage.Status = field.NewString(tableName, "status")
	_mqDeadLetterMessage.CreateTime = field.NewTime(tableName, "create_time")
	_mqDeadLetterMessage.UpdateTime = field.NewTime(tableName, "update_time")

	_mqDeadLetterMessage.fillFieldMap()

	return _mqDeadLetterMessage
}

// mqDeadLetterMessage Kafka死信消息表
type mqDeadLetterMessage struct {
	mqDeadLetterMessageDo mqDeadLetterMessageDo

	ALL          field.Asterisk
	ID           field.Uint64 // 主键ID
	EventID      field.String // 事件唯一ID
	Topic        field.String // 原始消息Topic
	PartitionID  field.Int32  // 原始消息分区
	OffsetID     field.Int64  // 原始消息偏移量
	OrderNo      field.String // 订单号
	RequestID    field.String // 请求ID
	TraceID      field.String // 链路追踪ID
	RetryCount   field.Int32  // 重试次数
	ErrorMessage field.String // 错误信息
	RawPayload   field.String // 原始消息内容（JSON）
	Status       field.String // 状态：PENDING-待处理，PROCESSING-处理中，SUCCESS-已处理，FAILED-最终失败，SKIPPED-跳过
	CreateTime   field.Time   // 创建时间
	UpdateTime   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m mqDeadLetterMessage) Table(newTableName string) *mqDeadLetterMessage {
	m.mqDeadLetterMessageDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqDeadLetterMessage) As(alias string) *mqDeadLetterMessage {
	m.mqDeadLetterMessageDo.DO = *(m.mqDeadLetterMessageDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqDeadLetterMessage) updateTableName(table string) *mqDeadLetterMessage {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.EventID = field.NewString(table, "event_id")
	m.Topic = field.NewString(table, "topic")
	m.PartitionID = field.NewInt32(table, "partition_id")
	m.OffsetID = field.NewInt64(table, "offset_id")
	m.OrderNo = field.NewString(table, "order_no")
	m.RequestID = field.NewString(table, "request_id")
	m.TraceID = field.NewString(table, "trace_id")
	m.RetryCount = field.NewInt32(table, "retry_count")
	m.ErrorMessage = field.NewString(table, "error_message")
	m.RawPayload = field.NewString(table, "raw_payload")
	m.Status = field.NewString(table, "status")
	m.CreateTime = field.NewTime(table, "create_time")
	m.UpdateTime = field.NewTime(table, "update_time")

	m.fillFieldMap()

	return m
}

func (m *mqDeadLetterMessage) WithContext(ctx context.Context) IMqDeadLetterMessageDo {
	return m.mqDeadLetterMessageDo.WithContext(ctx)
}

func (m mqDeadLetterMessage) TableName() string { return m.mqDeadLetterMessageDo.TableName() }

func (m mqDeadLetterMessage) Alias() string { return m.mqDeadLetterMessageDo.Alias() }

func (m mqDeadLetterMessage) Columns(cols ...field.Expr) gen.Columns {
	return m.mqDeadLetterMessageDo.Columns(cols...)
}

func (m *mqDeadLetterMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqDeadLetterMessage) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 14)
	m.fieldMap["id"] = m.ID
	m.fieldMap["event_id"] = m.EventID
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["partition_id"] = m.PartitionID
	m.fieldMap["offset_id"] = m.OffsetID
	m.fieldMap["order_no"] = m.OrderNo
	m.fieldMap["request_id"] = m.RequestID
	m.fieldMap["trace_id"] = m.TraceID
	m.fieldMap["retry_count"] = m.RetryCount
	m.fieldMap["error_message"] = m.ErrorMessage
	m.fieldMap["raw_payload"] = m.RawPayload
	m.fieldMap["status"] = m.Status
	m.fieldMap["create_time"] = m.CreateTime
	m.fieldMap["update_time"] = m.UpdateTime
}

func (m mqDeadLetterMessage) clone(db *gorm.DB) mqDeadLetterMessage {
	m.mqDeadLetterMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqDeadLetterMessage) replaceDB(db *gorm.DB) mqDeadLetterMessage {
	m.mqDeadLetterMessageDo.ReplaceDB(db)
	return m
}

type mqDeadLetterMessageDo struct{ gen.DO }

type IMqDeadLetterMessageDo interface {
	gen.SubQuery
	Debug() IMqDeadLetterMessageDo
	WithContext(ctx context.Context) IMqDeadLetterMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqDeadLetterMessageDo
	WriteDB() IMqDeadLetterMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqDeadLetterMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqDeadLetterMessageDo
	Not(conds ...gen.Condition) IMqDeadLetterMessageDo
	Or(conds ...gen.Condition) IMqDeadLetterMessageDo
	Select(conds ...field.Expr) IMqDeadLetterMessageDo
	Where(conds ...gen.Condition) IMqDeadLetterMessageDo
	Order(conds ...field.Expr) IMqDeadLetterMessageDo
	Distinct(cols ...field.Expr) IMqDeadLetterMessageDo
	Omit(cols ...field.Expr) IMqDeadLetterMessageDo
	Join(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo
	Group(cols ...field.Expr) IMqDeadLetterMessageDo
	Having(conds ...gen.Condition) IMqDeadLetterMessageDo
	Limit(limit int) IMqDeadLetterMessageDo
	Offset(offset int) IMqDeadLetterMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqDeadLetterMessageDo
	Unscoped() IMqDeadLetterMessageDo
	Create(values ...*model.MqDeadLetterMessage) error
	CreateInBatches(values []*model.MqDeadLetterMessage, batchSize int) error
	Save(values ...*model.MqDeadLetterMessage) error
	First() (*model.MqDeadLetterMessage, error)
	Take() (*model.MqDeadLetterMessage, error)
	Last() (*model.MqDeadLetterMessage, error)
	Find() ([]*model.MqDeadLetterMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqDeadLetterMessage, err error)
	FindInBatches(result *[]*model.MqDeadLetterMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqDeadLetterMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqDeadLetterMessageDo
	Assign(attrs ...field.AssignExpr) IMqDeadLetterMessageDo
	Joins(fields ...field.RelationField) IMqDeadLetterMessageDo
	Preload(fields ...field.RelationField) IMqDeadLetterMessageDo
	FirstOrInit() (*model.MqDeadLetterMessage, error)
	FirstOrCreate() (*model.MqDeadLetterMessage, error)
	FindByPage(offset int, limit int) (result []*model.MqDeadLetterMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqDeadLetterMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqDeadLetterMessageDo) Debug() IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Debug())
}

func (m mqDeadLetterMessageDo) WithContext(ctx context.Context) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqDeadLetterMessageDo) ReadDB() IMqDeadLetterMessageDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqDeadLetterMessageDo) WriteDB() IMqDeadLetterMessageDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqDeadLetterMessageDo) Session(config *gorm.Session) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqDeadLetterMessageDo) Clauses(conds ...clause.Expression) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqDeadLetterMessageDo) Returning(value interface{}, columns ...string) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqDeadLetterMessageDo) Not(conds ...gen.Condition) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqDeadLetterMessageDo) Or(conds ...gen.Condition) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqDeadLetterMessageDo) Select(conds ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqDeadLetterMessageDo) Where(conds ...gen.Condition) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqDeadLetterMessageDo) Order(conds ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqDeadLetterMessageDo) Distinct(cols ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqDeadLetterMessageDo) Omit(cols ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqDeadLetterMessageDo) Join(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqDeadLetterMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqDeadLetterMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqDeadLetterMessageDo) Group(cols ...field.Expr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqDeadLetterMessageDo) Having(conds ...gen.Condition) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqDeadLetterMessageDo) Limit(limit int) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqDeadLetterMessageDo) Offset(offset int) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqDeadLetterMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqDeadLetterMessageDo) Unscoped() IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqDeadLetterMessageDo) Create(values ...*model.MqDeadLetterMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqDeadLetterMessageDo) CreateInBatches(values []*model.MqDeadLetterMessage, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqDeadLetterMessageDo) Save(values ...*model.MqDeadLetterMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqDeadLetterMessageDo) First() (*model.MqDeadLetterMessage, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqDeadLetterMessage), nil
	}
}

func (m mqDeadLetterMessageDo) Take() (*model.MqDeadLetterMessage, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqDeadLetterMessage), nil
	}
}

func (m mqDeadLetterMessageDo) Last() (*model.MqDeadLetterMessage, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqDeadLetterMessage), nil
	}
}

func (m mqDeadLetterMessageDo) Find() ([]*model.MqDeadLetterMessage, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqDeadLetterMessage), err
}

func (m mqDeadLetterMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqDeadLetterMessage, err error) {
	buf := make([]*model.MqDeadLetterMessage, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqDeadLetterMessageDo) FindInBatches(result *[]*model.MqDeadLetterMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqDeadLetterMessageDo) Attrs(attrs ...field.AssignExpr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqDeadLetterMessageDo) Assign(attrs ...field.AssignExpr) IMqDeadLetterMessageDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqDeadLetterMessageDo) Joins(fields ...field.RelationField) IMqDeadLetterMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqDeadLetterMessageDo) Preload(fields ...field.RelationField) IMqDeadLetterMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqDeadLetterMessageDo) FirstOrInit() (*model.MqDeadLetterMessage, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqDeadLetterMessage), nil
	}
}

func (m mqDeadLetterMessageDo) FirstOrCreate() (*model.MqDeadLetterMessage, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqDeadLetterMessage), nil
	}
}

func (m mqDeadLetterMessageDo) FindByPage(offset int, limit int) (result []*model.MqDeadLetterMessage, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqDeadLetterMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqDeadLetterMessageDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqDeadLetterMessageDo) Delete(models ...*model.MqDeadLetterMessage) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqDeadLetterMessageDo) withDO(do gen.Dao) *mqDeadLetterMessageDo {
	m.DO = *do.(*gen.DO)
	return m
}
