// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/go-redis/redis/v8"
	"seckill-service/internal/biz"
	"seckill-service/internal/cache"
	"seckill-service/internal/conf"
	"seckill-service/internal/data"
	"seckill-service/internal/data/repo"
	"seckill-service/internal/job"
	"seckill-service/internal/kafka"
	"seckill-service/internal/server"
	"seckill-service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(s *conf.Server, d *conf.Data, k *conf.Kafka, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(d, logger)
	if err != nil {
		return nil, nil, err
	}
	seckillRepo := repo.NewMysqlRepo(dataData, logger)
	client := provideRedis(d)
	cacheRepo := repo.NewRedisRepo(client, logger)
	config := provideKafkaConfig(k)
	producer, err := kafka.NewProducer(config, logger)
	if err != nil {
		return nil, nil, err
	}
	rateLimiter := cache.NewRateLimiter(client)
	idempotentChecker := cache.NewIdempotentChecker(client)
	transaction := data.NewTransaction(dataData, logger)
	orderCancelService := biz.NewOrderCancelService(seckillRepo, cacheRepo, transaction, logger)
	delayQueue := job.NewDelayQueue(client, seckillRepo, cacheRepo, orderCancelService, logger)
	idGenerator := biz.NewIDGenerator(logger)
	seckillUsecase := biz.NewSeckillUsecase(seckillRepo, cacheRepo, producer, rateLimiter, idempotentChecker, delayQueue, orderCancelService, idGenerator, logger, transaction)
	seckillService := service.NewSeckillService(seckillUsecase, logger)
	grpcServer := server.NewGRPCServer(s, seckillService, logger)
	httpServer := server.NewHTTPServer(s, seckillService, logger)
	consumer, err := kafka.NewConsumer(config, seckillUsecase, producer, logger)
	if err != nil {
		return nil, nil, err
	}
	compensateTask := job.NewCompensateTask(client, seckillRepo, cacheRepo, logger)
	backgroundTasks := NewBackgroundTasks(consumer, delayQueue, compensateTask, seckillUsecase)
	app := newApp(logger, grpcServer, httpServer, backgroundTasks)
	return app, func() {
	}, nil
}

// wire.go:

// provideRedis 提供 Redis 客户端
func provideRedis(c *conf.Data) *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr:     c.Redis.Addr,
		Password: c.Redis.Password,
		DB:       int(c.Redis.Db),
	})
}

func provideKafkaConfig(k *conf.Kafka) *kafka.Config {
	return kafka.FromProto(k)
}

// BackgroundTasks 后台任务启动器
type BackgroundTasks struct {
	Consumer       *kafka.Consumer
	DelayQueue     *job.DelayQueue
	CompensateTask *job.CompensateTask
	SeckillUsecase *biz.SeckillUsecase
}

// NewBackgroundTasks 创建后台任务启动器
func NewBackgroundTasks(
	consumer *kafka.Consumer,
	delayQueue *job.DelayQueue,
	compensateTask *job.CompensateTask,
	seckillUsecase *biz.SeckillUsecase,
) *BackgroundTasks {
	return &BackgroundTasks{
		Consumer:       consumer,
		DelayQueue:     delayQueue,
		CompensateTask: compensateTask,
		SeckillUsecase: seckillUsecase,
	}
}

// Start 启动所有后台任务
func (b *BackgroundTasks) Start(ctx context.Context, logger log.Logger) {
	helper := log.NewHelper(logger)

	helper.Info("开始预热缓存...")
	if err := b.SeckillUsecase.WarmUpSeckillCache(ctx, 1); err != nil {
		helper.Warnf("预热缓存失败: %v", err)
	} else {
		helper.Info("缓存预热完成")
	}

	helper.Info("启动 Kafka 主消费者...")
	if err := b.Consumer.Start(ctx); err != nil {
		helper.Errorf("启动 Kafka 消费者失败: %v", err)
	}

	helper.Info("启动延迟队列...")
	go b.DelayQueue.Start(ctx)

	helper.Info("启动补偿任务...")
	go b.CompensateTask.Start(ctx)

	helper.Info("所有后台任务启动成功")
}

// Stop 停止所有后台任务
func (b *BackgroundTasks) Stop(ctx context.Context, logger log.Logger) {
	helper := log.NewHelper(logger)
	helper.Info("正在停止后台任务...")

	if err := b.Consumer.Stop(); err != nil {
		helper.Errorf("停止 Kafka 消费者失败: %v", err)
	}

	helper.Info("所有后台任务已停止")
}

func newApp(logger log.Logger, gs *grpc.Server, hs *http.Server, bg *BackgroundTasks) *kratos.App {
	return kratos.New(kratos.ID("seckill-service"), kratos.Name("seckill-service"), kratos.Version("1.0.0"), kratos.Metadata(map[string]string{}), kratos.Logger(logger), kratos.Server(gs, hs), kratos.AfterStart(func(ctx context.Context) error {
		bg.Start(ctx, logger)
		return nil
	}), kratos.BeforeStop(func(ctx context.Context) error {
		bg.Stop(ctx, logger)
		return nil
	}),
	)
}
