// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"seckill-service/internal/biz"
	"seckill-service/internal/conf"
	"seckill-service/internal/data"
	"seckill-service/internal/server"
	"seckill-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	seckillRepo := data.NewSeckillRepo(dataData, logger)
	transaction := data.NewTransaction(dataData, logger)
	seckillUsecase := biz.NewSeckillUsecase(seckillRepo, logger, transaction)
	seckillService := service.NewSeckillService(seckillUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, seckillService, logger)
	httpServer := server.NewHTTPServer(confServer, seckillService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
