// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeckillOrder = "seckill_order"

// SeckillOrder 秒杀订单表
type SeckillOrder struct {
	ID           uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:订单ID" json:"id"`                                                                               // 订单ID
	OrderNo      string     `gorm:"column:order_no;type:varchar(32);not null;uniqueIndex:uk_order_no,priority:1;comment:订单编号" json:"order_no"`                                                         // 订单编号
	UserID       uint64     `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:uk_user_activity_product,priority:1;index:idx_user_id,priority:1;comment:用户ID" json:"user_id"`             // 用户ID
	ActivityID   uint64     `gorm:"column:activity_id;type:bigint unsigned;not null;uniqueIndex:uk_user_activity_product,priority:2;index:idx_activity_id,priority:1;comment:活动ID" json:"activity_id"` // 活动ID
	ProductID    uint64     `gorm:"column:product_id;type:bigint unsigned;not null;uniqueIndex:uk_user_activity_product,priority:3;comment:商品ID" json:"product_id"`                                    // 商品ID
	SkuID        uint64     `gorm:"column:sku_id;type:bigint unsigned;not null;comment:秒杀商品关联ID" json:"sku_id"`                                                                                        // 秒杀商品关联ID
	ProductName  string     `gorm:"column:product_name;type:varchar(200);not null;comment:商品名称（快照）" json:"product_name"`                                                                               // 商品名称（快照）
	ProductImage string     `gorm:"column:product_image;type:varchar(500);not null;comment:商品图片（快照）" json:"product_image"`                                                                             // 商品图片（快照）
	SeckillPrice uint64     `gorm:"column:seckill_price;type:bigint unsigned;not null;comment:秒杀单价（快照，单位：分）" json:"seckill_price"`                                                                     // 秒杀单价（快照，单位：分）
	Quantity     *uint32    `gorm:"column:quantity;type:int unsigned;not null;default:1;comment:购买数量" json:"quantity"`                                                                                 // 购买数量
	OrderAmount  uint64     `gorm:"column:order_amount;type:bigint unsigned;not null;comment:订单总金额（单位：分）" json:"order_amount"`                                                                         // 订单总金额（单位：分）
	CouponID     *uint64    `gorm:"column:coupon_id;type:bigint unsigned;comment:使用的优惠券ID" json:"coupon_id"`                                                                                           // 使用的优惠券ID
	AddressID    *uint64    `gorm:"column:address_id;type:bigint unsigned;comment:收货地址ID" json:"address_id"`                                                                                           // 收货地址ID
	Status       uint32     `gorm:"column:status;type:tinyint unsigned;not null;index:idx_status,priority:1;comment:状态：0-待支付，1-已支付，2-已取消，3-已退款" json:"status"`                                         // 状态：0-待支付，1-已支付，2-已取消，3-已退款
	PayTime      *time.Time `gorm:"column:pay_time;type:datetime;comment:支付时间" json:"pay_time"`                                                                                                        // 支付时间
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                                               // 创建时间
	UpdateTime   *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                                                               // 更新时间
}

// TableName SeckillOrder's table name
func (*SeckillOrder) TableName() string {
	return TableNameSeckillOrder
}
