// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Coupon          *coupon
	OrderShipping   *orderShipping
	SeckillActivity *seckillActivity
	SeckillOrder    *seckillOrder
	SeckillSku      *seckillSku
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Coupon = &Q.Coupon
	OrderShipping = &Q.OrderShipping
	SeckillActivity = &Q.SeckillActivity
	SeckillOrder = &Q.SeckillOrder
	SeckillSku = &Q.SeckillSku
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Coupon:          newCoupon(db, opts...),
		OrderShipping:   newOrderShipping(db, opts...),
		SeckillActivity: newSeckillActivity(db, opts...),
		SeckillOrder:    newSeckillOrder(db, opts...),
		SeckillSku:      newSeckillSku(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Coupon          coupon
	OrderShipping   orderShipping
	SeckillActivity seckillActivity
	SeckillOrder    seckillOrder
	SeckillSku      seckillSku
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Coupon:          q.Coupon.clone(db),
		OrderShipping:   q.OrderShipping.clone(db),
		SeckillActivity: q.SeckillActivity.clone(db),
		SeckillOrder:    q.SeckillOrder.clone(db),
		SeckillSku:      q.SeckillSku.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Coupon:          q.Coupon.replaceDB(db),
		OrderShipping:   q.OrderShipping.replaceDB(db),
		SeckillActivity: q.SeckillActivity.replaceDB(db),
		SeckillOrder:    q.SeckillOrder.replaceDB(db),
		SeckillSku:      q.SeckillSku.replaceDB(db),
	}
}

type queryCtx struct {
	Coupon          ICouponDo
	OrderShipping   IOrderShippingDo
	SeckillActivity ISeckillActivityDo
	SeckillOrder    ISeckillOrderDo
	SeckillSku      ISeckillSkuDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Coupon:          q.Coupon.WithContext(ctx),
		OrderShipping:   q.OrderShipping.WithContext(ctx),
		SeckillActivity: q.SeckillActivity.WithContext(ctx),
		SeckillOrder:    q.SeckillOrder.WithContext(ctx),
		SeckillSku:      q.SeckillSku.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
