// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Kafka         *Kafka                 `protobuf:"bytes,3,opt,name=kafka,proto3" json:"kafka,omitempty"`
	Observability *Observability         `protobuf:"bytes,4,opt,name=observability,proto3" json:"observability,omitempty"`
	Nacos         *Nacos                 `protobuf:"bytes,5,opt,name=nacos,proto3" json:"nacos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetKafka() *Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetNacos() *Nacos {
	if x != nil {
		return x.Nacos
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDb        *Data_Database         `protobuf:"bytes,1,opt,name=user_db,json=userDb,proto3" json:"user_db,omitempty"`
	ProductDb     *Data_Database         `protobuf:"bytes,2,opt,name=product_db,json=productDb,proto3" json:"product_db,omitempty"`
	CoreDb        *Data_Database         `protobuf:"bytes,3,opt,name=core_db,json=coreDb,proto3" json:"core_db,omitempty"`
	PayDb         *Data_Database         `protobuf:"bytes,4,opt,name=pay_db,json=payDb,proto3" json:"pay_db,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,5,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetUserDb() *Data_Database {
	if x != nil {
		return x.UserDb
	}
	return nil
}

func (x *Data) GetProductDb() *Data_Database {
	if x != nil {
		return x.ProductDb
	}
	return nil
}

func (x *Data) GetCoreDb() *Data_Database {
	if x != nil {
		return x.CoreDb
	}
	return nil
}

func (x *Data) GetPayDb() *Data_Database {
	if x != nil {
		return x.PayDb
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,3,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Producer      *Kafka_Producer        `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	Consumer      *Kafka_Consumer        `protobuf:"bytes,6,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topics        *Kafka_Topics          `protobuf:"bytes,7,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Kafka) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Kafka) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *Kafka) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Kafka) GetProducer() *Kafka_Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *Kafka) GetConsumer() *Kafka_Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *Kafka) GetTopics() *Kafka_Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` //是否启用可观测性
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	OtelEndpoint  string                 `protobuf:"bytes,4,opt,name=otel_endpoint,json=otelEndpoint,proto3" json:"otel_endpoint,omitempty"`     // OpenTelemetry 收集器地址
	SampleRatio   float64                `protobuf:"fixed64,5,opt,name=sample_ratio,json=sampleRatio,proto3" json:"sample_ratio,omitempty"`      // 链路采样率
	EnableMetrics bool                   `protobuf:"varint,6,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"` // 是否启用指标采集
	MetricsAddr   string                 `protobuf:"bytes,7,opt,name=metrics_addr,json=metricsAddr,proto3" json:"metrics_addr,omitempty"`        // Prometheus 指标暴露地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Observability) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Observability) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Observability) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Observability) GetOtelEndpoint() string {
	if x != nil {
		return x.OtelEndpoint
	}
	return ""
}

func (x *Observability) GetSampleRatio() float64 {
	if x != nil {
		return x.SampleRatio
	}
	return 0
}

func (x *Observability) GetEnableMetrics() bool {
	if x != nil {
		return x.EnableMetrics
	}
	return false
}

func (x *Observability) GetMetricsAddr() string {
	if x != nil {
		return x.MetricsAddr
	}
	return ""
}

type Nacos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`                 // 配置分组
	DataId        string                 `protobuf:"bytes,5,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // 配置数据ID
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	ServiceName   string                 `protobuf:"bytes,8,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nacos) Reset() {
	*x = Nacos{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos) ProtoMessage() {}

func (x *Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos.ProtoReflect.Descriptor instead.
func (*Nacos) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Nacos) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Nacos) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Nacos) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Nacos) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Nacos) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *Nacos) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Nacos) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Nacos) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,5,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

// Producer 配置
type Kafka_Producer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxMessageBytes   int32                  `protobuf:"varint,1,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	RequiredAcks      int32                  `protobuf:"varint,2,opt,name=required_acks,json=requiredAcks,proto3" json:"required_acks,omitempty"`
	Compression       string                 `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"`
	RetryMax          int32                  `protobuf:"varint,4,opt,name=retry_max,json=retryMax,proto3" json:"retry_max,omitempty"`
	RetryBackoff      *durationpb.Duration   `protobuf:"bytes,5,opt,name=retry_backoff,json=retryBackoff,proto3" json:"retry_backoff,omitempty"`
	Timeout           *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	EnableIdempotence bool                   `protobuf:"varint,7,opt,name=enable_idempotence,json=enableIdempotence,proto3" json:"enable_idempotence,omitempty"` // 是否启用幂等性
	MaxInFlight       int32                  `protobuf:"varint,8,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`                 // 最大在途请求数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Kafka_Producer) Reset() {
	*x = Kafka_Producer{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Producer) ProtoMessage() {}

func (x *Kafka_Producer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Producer.ProtoReflect.Descriptor instead.
func (*Kafka_Producer) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Kafka_Producer) GetMaxMessageBytes() int32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

func (x *Kafka_Producer) GetRequiredAcks() int32 {
	if x != nil {
		return x.RequiredAcks
	}
	return 0
}

func (x *Kafka_Producer) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *Kafka_Producer) GetRetryMax() int32 {
	if x != nil {
		return x.RetryMax
	}
	return 0
}

func (x *Kafka_Producer) GetRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.RetryBackoff
	}
	return nil
}

func (x *Kafka_Producer) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Kafka_Producer) GetEnableIdempotence() bool {
	if x != nil {
		return x.EnableIdempotence
	}
	return false
}

func (x *Kafka_Producer) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

// Consumer 配置
type Kafka_Consumer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionTimeout    *durationpb.Duration   `protobuf:"bytes,1,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	MaxProcessingTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_processing_time,json=maxProcessingTime,proto3" json:"max_processing_time,omitempty"`
	FetchMinBytes     int32                  `protobuf:"varint,4,opt,name=fetch_min_bytes,json=fetchMinBytes,proto3" json:"fetch_min_bytes,omitempty"`
	FetchMaxBytes     int32                  `protobuf:"varint,5,opt,name=fetch_max_bytes,json=fetchMaxBytes,proto3" json:"fetch_max_bytes,omitempty"`
	MaxWaitTime       *durationpb.Duration   `protobuf:"bytes,6,opt,name=max_wait_time,json=maxWaitTime,proto3" json:"max_wait_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Kafka_Consumer) Reset() {
	*x = Kafka_Consumer{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Consumer) ProtoMessage() {}

func (x *Kafka_Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Consumer.ProtoReflect.Descriptor instead.
func (*Kafka_Consumer) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Kafka_Consumer) GetSessionTimeout() *durationpb.Duration {
	if x != nil {
		return x.SessionTimeout
	}
	return nil
}

func (x *Kafka_Consumer) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *Kafka_Consumer) GetMaxProcessingTime() *durationpb.Duration {
	if x != nil {
		return x.MaxProcessingTime
	}
	return nil
}

func (x *Kafka_Consumer) GetFetchMinBytes() int32 {
	if x != nil {
		return x.FetchMinBytes
	}
	return 0
}

func (x *Kafka_Consumer) GetFetchMaxBytes() int32 {
	if x != nil {
		return x.FetchMaxBytes
	}
	return 0
}

func (x *Kafka_Consumer) GetMaxWaitTime() *durationpb.Duration {
	if x != nil {
		return x.MaxWaitTime
	}
	return nil
}

// 主题配置
type Kafka_Topics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeckillOrder     string                 `protobuf:"bytes,1,opt,name=seckill_order,json=seckillOrder,proto3" json:"seckill_order,omitempty"`    // 秒杀订单主Topic
	SeckillResult    string                 `protobuf:"bytes,2,opt,name=seckill_result,json=seckillResult,proto3" json:"seckill_result,omitempty"` // 秒杀结果Topic
	SeckillDlq       string                 `protobuf:"bytes,3,opt,name=seckill_dlq,json=seckillDlq,proto3" json:"seckill_dlq,omitempty"`          // 死信队列Topic
	SeckillRetry     string                 `protobuf:"bytes,4,opt,name=seckill_retry,json=seckillRetry,proto3" json:"seckill_retry,omitempty"`    // 重试队列Topic（延迟队列）
	SeckillOrderPaid string                 `protobuf:"bytes,5,opt,name=seckill_order_paid,json=seckillOrderPaid,proto3" json:"seckill_order_paid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Kafka_Topics) Reset() {
	*x = Kafka_Topics{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Topics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Topics) ProtoMessage() {}

func (x *Kafka_Topics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Topics.ProtoReflect.Descriptor instead.
func (*Kafka_Topics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Kafka_Topics) GetSeckillOrder() string {
	if x != nil {
		return x.SeckillOrder
	}
	return ""
}

func (x *Kafka_Topics) GetSeckillResult() string {
	if x != nil {
		return x.SeckillResult
	}
	return ""
}

func (x *Kafka_Topics) GetSeckillDlq() string {
	if x != nil {
		return x.SeckillDlq
	}
	return ""
}

func (x *Kafka_Topics) GetSeckillRetry() string {
	if x != nil {
		return x.SeckillRetry
	}
	return ""
}

func (x *Kafka_Topics) GetSeckillOrderPaid() string {
	if x != nil {
		return x.SeckillOrderPaid
	}
	return ""
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xf0\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12'\n" +
	"\x05kafka\x18\x03 \x01(\v2\x11.kratos.api.KafkaR\x05kafka\x12?\n" +
	"\robservability\x18\x04 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\x12'\n" +
	"\x05nacos\x18\x05 \x01(\v2\x11.kratos.api.NacosR\x05nacos\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x8c\x04\n" +
	"\x04Data\x122\n" +
	"\auser_db\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\x06userDb\x128\n" +
	"\n" +
	"product_db\x18\x02 \x01(\v2\x19.kratos.api.Data.DatabaseR\tproductDb\x122\n" +
	"\acore_db\x18\x03 \x01(\v2\x19.kratos.api.Data.DatabaseR\x06coreDb\x120\n" +
	"\x06pay_db\x18\x04 \x01(\v2\x19.kratos.api.Data.DatabaseR\x05payDb\x12,\n" +
	"\x05redis\x18\x05 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xc5\x01\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12<\n" +
	"\fread_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"\xc6\t\n" +
	"\x05Kafka\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0econsumer_group\x18\x03 \x01(\tR\rconsumerGroup\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x126\n" +
	"\bproducer\x18\x05 \x01(\v2\x1a.kratos.api.Kafka.ProducerR\bproducer\x126\n" +
	"\bconsumer\x18\x06 \x01(\v2\x1a.kratos.api.Kafka.ConsumerR\bconsumer\x120\n" +
	"\x06topics\x18\a \x01(\v2\x18.kratos.api.Kafka.TopicsR\x06topics\x1a\xe2\x02\n" +
	"\bProducer\x12*\n" +
	"\x11max_message_bytes\x18\x01 \x01(\x05R\x0fmaxMessageBytes\x12#\n" +
	"\rrequired_acks\x18\x02 \x01(\x05R\frequiredAcks\x12 \n" +
	"\vcompression\x18\x03 \x01(\tR\vcompression\x12\x1b\n" +
	"\tretry_max\x18\x04 \x01(\x05R\bretryMax\x12>\n" +
	"\rretry_backoff\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fretryBackoff\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12-\n" +
	"\x12enable_idempotence\x18\a \x01(\bR\x11enableIdempotence\x12\"\n" +
	"\rmax_in_flight\x18\b \x01(\x05R\vmaxInFlight\x1a\xf2\x02\n" +
	"\bConsumer\x12B\n" +
	"\x0fsession_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0esessionTimeout\x12H\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12I\n" +
	"\x13max_processing_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11maxProcessingTime\x12&\n" +
	"\x0ffetch_min_bytes\x18\x04 \x01(\x05R\rfetchMinBytes\x12&\n" +
	"\x0ffetch_max_bytes\x18\x05 \x01(\x05R\rfetchMaxBytes\x12=\n" +
	"\rmax_wait_time\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vmaxWaitTime\x1a\xc8\x01\n" +
	"\x06Topics\x12#\n" +
	"\rseckill_order\x18\x01 \x01(\tR\fseckillOrder\x12%\n" +
	"\x0eseckill_result\x18\x02 \x01(\tR\rseckillResult\x12\x1f\n" +
	"\vseckill_dlq\x18\x03 \x01(\tR\n" +
	"seckillDlq\x12#\n" +
	"\rseckill_retry\x18\x04 \x01(\tR\fseckillRetry\x12,\n" +
	"\x12seckill_order_paid\x18\x05 \x01(\tR\x10seckillOrderPaid\"\xf0\x01\n" +
	"\rObservability\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12#\n" +
	"\rotel_endpoint\x18\x04 \x01(\tR\fotelEndpoint\x12!\n" +
	"\fsample_ratio\x18\x05 \x01(\x01R\vsampleRatio\x12%\n" +
	"\x0eenable_metrics\x18\x06 \x01(\bR\renableMetrics\x12!\n" +
	"\fmetrics_addr\x18\a \x01(\tR\vmetricsAddr\"\xdd\x01\n" +
	"\x05Nacos\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x17\n" +
	"\adata_id\x18\x05 \x01(\tR\x06dataId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12!\n" +
	"\fservice_name\x18\b \x01(\tR\vserviceNameB$Z\"seckill-service/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Kafka)(nil),               // 3: kratos.api.Kafka
	(*Observability)(nil),       // 4: kratos.api.Observability
	(*Nacos)(nil),               // 5: kratos.api.Nacos
	(*Server_HTTP)(nil),         // 6: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 7: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 8: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 9: kratos.api.Data.Redis
	(*Kafka_Producer)(nil),      // 10: kratos.api.Kafka.Producer
	(*Kafka_Consumer)(nil),      // 11: kratos.api.Kafka.Consumer
	(*Kafka_Topics)(nil),        // 12: kratos.api.Kafka.Topics
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.kafka:type_name -> kratos.api.Kafka
	4,  // 3: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	5,  // 4: kratos.api.Bootstrap.nacos:type_name -> kratos.api.Nacos
	6,  // 5: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	7,  // 6: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	8,  // 7: kratos.api.Data.user_db:type_name -> kratos.api.Data.Database
	8,  // 8: kratos.api.Data.product_db:type_name -> kratos.api.Data.Database
	8,  // 9: kratos.api.Data.core_db:type_name -> kratos.api.Data.Database
	8,  // 10: kratos.api.Data.pay_db:type_name -> kratos.api.Data.Database
	9,  // 11: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	10, // 12: kratos.api.Kafka.producer:type_name -> kratos.api.Kafka.Producer
	11, // 13: kratos.api.Kafka.consumer:type_name -> kratos.api.Kafka.Consumer
	12, // 14: kratos.api.Kafka.topics:type_name -> kratos.api.Kafka.Topics
	13, // 15: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 16: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 17: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	13, // 18: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	13, // 19: kratos.api.Kafka.Producer.retry_backoff:type_name -> google.protobuf.Duration
	13, // 20: kratos.api.Kafka.Producer.timeout:type_name -> google.protobuf.Duration
	13, // 21: kratos.api.Kafka.Consumer.session_timeout:type_name -> google.protobuf.Duration
	13, // 22: kratos.api.Kafka.Consumer.heartbeat_interval:type_name -> google.protobuf.Duration
	13, // 23: kratos.api.Kafka.Consumer.max_processing_time:type_name -> google.protobuf.Duration
	13, // 24: kratos.api.Kafka.Consumer.max_wait_time:type_name -> google.protobuf.Duration
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
