// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageOutbox = "message_outbox"

// MessageOutbox 本地消息表
type MessageOutbox struct {
	ID            uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                    // 主键ID
	EventID       string     `gorm:"column:event_id;type:varchar(64);not null;uniqueIndex:uk_event_id,priority:1;comment:事件唯一ID" json:"event_id"`            // 事件唯一ID
	AggregateType string     `gorm:"column:aggregate_type;type:varchar(64);not null;comment:聚合根类型（Order/User等）" json:"aggregate_type"`                       // 聚合根类型（Order/User等）
	AggregateID   string     `gorm:"column:aggregate_id;type:varchar(64);not null;comment:聚合根ID（订单号/用户ID等）" json:"aggregate_id"`                             // 聚合根ID（订单号/用户ID等）
	Topic         string     `gorm:"column:topic;type:varchar(128);not null;comment:Kafka Topic" json:"topic"`                                               // Kafka Topic
	Payload       string     `gorm:"column:payload;type:json;not null;comment:事件负载（JSON格式）" json:"payload"`                                                  // 事件负载（JSON格式）
	Status        int32      `gorm:"column:status;type:tinyint;not null;index:idx_status_next_retry,priority:1;comment:状态：0-待发送，1-已发送，2-发送失败" json:"status"` // 状态：0-待发送，1-已发送，2-发送失败
	RetryCount    int32      `gorm:"column:retry_count;type:int;not null;comment:已重试次数" json:"retry_count"`                                                  // 已重试次数
	NextRetryAt   *time.Time `gorm:"column:next_retry_at;type:datetime;index:idx_status_next_retry,priority:2;comment:下次重试时间（指数退避）" json:"next_retry_at"`    // 下次重试时间（指数退避）
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                      // 更新时间
}

// TableName MessageOutbox's table name
func (*MessageOutbox) TableName() string {
	return TableNameMessageOutbox
}
