// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqDeadLetterMessage = "mq_dead_letter_message"

// MqDeadLetterMessage Kafka死信消息表
type MqDeadLetterMessage struct {
	ID           uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                    // 主键ID
	EventID      string     `gorm:"column:event_id;type:varchar(64);not null;uniqueIndex:uk_event_id,priority:1;comment:事件唯一ID" json:"event_id"`                                                                            // 事件唯一ID
	Topic        string     `gorm:"column:topic;type:varchar(128);not null;comment:原始消息Topic" json:"topic"`                                                                                                                 // 原始消息Topic
	PartitionID  int32      `gorm:"column:partition_id;type:int;not null;comment:原始消息分区" json:"partition_id"`                                                                                                               // 原始消息分区
	OffsetID     int64      `gorm:"column:offset_id;type:bigint;not null;comment:原始消息偏移量" json:"offset_id"`                                                                                                                 // 原始消息偏移量
	OrderNo      string     `gorm:"column:order_no;type:varchar(32);not null;index:idx_order_no,priority:1;comment:订单号" json:"order_no"`                                                                                    // 订单号
	RequestID    string     `gorm:"column:request_id;type:varchar(64);not null;comment:请求ID" json:"request_id"`                                                                                                             // 请求ID
	TraceID      string     `gorm:"column:trace_id;type:varchar(64);not null;comment:链路追踪ID" json:"trace_id"`                                                                                                               // 链路追踪ID
	RetryCount   int32      `gorm:"column:retry_count;type:int;not null;comment:重试次数" json:"retry_count"`                                                                                                                   // 重试次数
	ErrorMessage string     `gorm:"column:error_message;type:varchar(512);not null;comment:错误信息" json:"error_message"`                                                                                                      // 错误信息
	RawPayload   string     `gorm:"column:raw_payload;type:longtext;not null;comment:原始消息内容（JSON）" json:"raw_payload"`                                                                                                      // 原始消息内容（JSON）
	Status       *string    `gorm:"column:status;type:varchar(16);not null;index:idx_status_create_time,priority:1;default:PENDING;comment:状态：PENDING-待处理，PROCESSING-处理中，SUCCESS-已处理，FAILED-最终失败，SKIPPED-跳过" json:"status"` // 状态：PENDING-待处理，PROCESSING-处理中，SUCCESS-已处理，FAILED-最终失败，SKIPPED-跳过
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;not null;index:idx_status_create_time,priority:2;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                            // 创建时间
	UpdateTime   *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                                                                                    // 更新时间
}

// TableName MqDeadLetterMessage's table name
func (*MqDeadLetterMessage) TableName() string {
	return TableNameMqDeadLetterMessage
}
