server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  user_db:
    driver: mysql
    source: root:1256@tcp(127.0.0.1:3306)/seckill_user?charset=utf8mb4&parseTime=True&loc=Local
  product_db:
    driver: mysql
    source: root:1256@tcp(127.0.0.1:3306)/seckill_product?charset=utf8mb4&parseTime=True&loc=Local
  core_db:
    driver: mysql
    source: root:1256@tcp(127.0.0.1:3306)/seckill_core?charset=utf8mb4&parseTime=True&loc=Local
  pay_db:
    driver: mysql
    source: root:1256@tcp(127.0.0.1:3306)/seckill_pay?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
redis:
  addr: 127.0.0.1:3306
  password: admin123
  db: 0
  read_timeout: 0.2s
  write_timeout: 0.2s