// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: seckill/v1/seckill.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSeckillCreateSeckillOrder = "/api.seckill.v1.Seckill/CreateSeckillOrder"
const OperationSeckillGetCurrentActivity = "/api.seckill.v1.Seckill/GetCurrentActivity"
const OperationSeckillGetSeckillOrder = "/api.seckill.v1.Seckill/GetSeckillOrder"
const OperationSeckillGetSeckillResult = "/api.seckill.v1.Seckill/GetSeckillResult"
const OperationSeckillPaySeckillOrder = "/api.seckill.v1.Seckill/PaySeckillOrder"
const OperationSeckillSeckillProductDetail = "/api.seckill.v1.Seckill/SeckillProductDetail"
const OperationSeckillSeckillProducts = "/api.seckill.v1.Seckill/SeckillProducts"

type SeckillHTTPServer interface {
	// CreateSeckillOrder 秒杀下单（核心高并发接口）
	CreateSeckillOrder(context.Context, *CreateSeckillOrderRequest) (*CreateSeckillOrderResponse, error)
	// GetCurrentActivity 秒杀活动信息
	GetCurrentActivity(context.Context, *GetCurrentActivityRequest) (*GetCurrentActivityResponse, error)
	// GetSeckillOrder 查询秒杀订单
	GetSeckillOrder(context.Context, *GetSeckillOrderRequest) (*GetSeckillOrderResponse, error)
	// GetSeckillResult 查询秒杀结果
	GetSeckillResult(context.Context, *GetSeckillResultRequest) (*GetSeckillResultResponse, error)
	// PaySeckillOrder 支付秒杀订单
	PaySeckillOrder(context.Context, *PaySeckillOrderRequest) (*PaySeckillOrderResponse, error)
	// SeckillProductDetail 查询秒杀商品详情
	SeckillProductDetail(context.Context, *SeckillProductDetailRequest) (*SeckillProductDetailResponse, error)
	// SeckillProducts 查询秒杀商品列表
	SeckillProducts(context.Context, *SeckillProductsRequest) (*SeckillProductsResponse, error)
}

func RegisterSeckillHTTPServer(s *http.Server, srv SeckillHTTPServer) {
	r := s.Route("/")
	r.GET("/seckill/products", _Seckill_SeckillProducts0_HTTP_Handler(srv))
	r.GET("/seckill/product/{product_id}", _Seckill_SeckillProductDetail0_HTTP_Handler(srv))
	r.GET("/api/v1/seckill/activity/current", _Seckill_GetCurrentActivity0_HTTP_Handler(srv))
	r.POST("/seckill/order", _Seckill_CreateSeckillOrder0_HTTP_Handler(srv))
	r.GET("/seckill/order/{order_no}", _Seckill_GetSeckillOrder0_HTTP_Handler(srv))
	r.GET("/api/v1/seckill/result", _Seckill_GetSeckillResult0_HTTP_Handler(srv))
	r.POST("/seckill/order/pay", _Seckill_PaySeckillOrder0_HTTP_Handler(srv))
}

func _Seckill_SeckillProducts0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeckillProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillSeckillProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SeckillProducts(ctx, req.(*SeckillProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeckillProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_SeckillProductDetail0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeckillProductDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillSeckillProductDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SeckillProductDetail(ctx, req.(*SeckillProductDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeckillProductDetailResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_GetCurrentActivity0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentActivityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillGetCurrentActivity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentActivity(ctx, req.(*GetCurrentActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentActivityResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_CreateSeckillOrder0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSeckillOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillCreateSeckillOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSeckillOrder(ctx, req.(*CreateSeckillOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSeckillOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_GetSeckillOrder0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeckillOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillGetSeckillOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeckillOrder(ctx, req.(*GetSeckillOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeckillOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_GetSeckillResult0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeckillResultRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillGetSeckillResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeckillResult(ctx, req.(*GetSeckillResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeckillResultResponse)
		return ctx.Result(200, reply)
	}
}

func _Seckill_PaySeckillOrder0_HTTP_Handler(srv SeckillHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PaySeckillOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeckillPaySeckillOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PaySeckillOrder(ctx, req.(*PaySeckillOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PaySeckillOrderResponse)
		return ctx.Result(200, reply)
	}
}

type SeckillHTTPClient interface {
	// CreateSeckillOrder 秒杀下单（核心高并发接口）
	CreateSeckillOrder(ctx context.Context, req *CreateSeckillOrderRequest, opts ...http.CallOption) (rsp *CreateSeckillOrderResponse, err error)
	// GetCurrentActivity 秒杀活动信息
	GetCurrentActivity(ctx context.Context, req *GetCurrentActivityRequest, opts ...http.CallOption) (rsp *GetCurrentActivityResponse, err error)
	// GetSeckillOrder 查询秒杀订单
	GetSeckillOrder(ctx context.Context, req *GetSeckillOrderRequest, opts ...http.CallOption) (rsp *GetSeckillOrderResponse, err error)
	// GetSeckillResult 查询秒杀结果
	GetSeckillResult(ctx context.Context, req *GetSeckillResultRequest, opts ...http.CallOption) (rsp *GetSeckillResultResponse, err error)
	// PaySeckillOrder 支付秒杀订单
	PaySeckillOrder(ctx context.Context, req *PaySeckillOrderRequest, opts ...http.CallOption) (rsp *PaySeckillOrderResponse, err error)
	// SeckillProductDetail 查询秒杀商品详情
	SeckillProductDetail(ctx context.Context, req *SeckillProductDetailRequest, opts ...http.CallOption) (rsp *SeckillProductDetailResponse, err error)
	// SeckillProducts 查询秒杀商品列表
	SeckillProducts(ctx context.Context, req *SeckillProductsRequest, opts ...http.CallOption) (rsp *SeckillProductsResponse, err error)
}

type SeckillHTTPClientImpl struct {
	cc *http.Client
}

func NewSeckillHTTPClient(client *http.Client) SeckillHTTPClient {
	return &SeckillHTTPClientImpl{client}
}

// CreateSeckillOrder 秒杀下单（核心高并发接口）
func (c *SeckillHTTPClientImpl) CreateSeckillOrder(ctx context.Context, in *CreateSeckillOrderRequest, opts ...http.CallOption) (*CreateSeckillOrderResponse, error) {
	var out CreateSeckillOrderResponse
	pattern := "/seckill/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSeckillCreateSeckillOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCurrentActivity 秒杀活动信息
func (c *SeckillHTTPClientImpl) GetCurrentActivity(ctx context.Context, in *GetCurrentActivityRequest, opts ...http.CallOption) (*GetCurrentActivityResponse, error) {
	var out GetCurrentActivityResponse
	pattern := "/api/v1/seckill/activity/current"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSeckillGetCurrentActivity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSeckillOrder 查询秒杀订单
func (c *SeckillHTTPClientImpl) GetSeckillOrder(ctx context.Context, in *GetSeckillOrderRequest, opts ...http.CallOption) (*GetSeckillOrderResponse, error) {
	var out GetSeckillOrderResponse
	pattern := "/seckill/order/{order_no}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSeckillGetSeckillOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSeckillResult 查询秒杀结果
func (c *SeckillHTTPClientImpl) GetSeckillResult(ctx context.Context, in *GetSeckillResultRequest, opts ...http.CallOption) (*GetSeckillResultResponse, error) {
	var out GetSeckillResultResponse
	pattern := "/api/v1/seckill/result"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSeckillGetSeckillResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PaySeckillOrder 支付秒杀订单
func (c *SeckillHTTPClientImpl) PaySeckillOrder(ctx context.Context, in *PaySeckillOrderRequest, opts ...http.CallOption) (*PaySeckillOrderResponse, error) {
	var out PaySeckillOrderResponse
	pattern := "/seckill/order/pay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSeckillPaySeckillOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SeckillProductDetail 查询秒杀商品详情
func (c *SeckillHTTPClientImpl) SeckillProductDetail(ctx context.Context, in *SeckillProductDetailRequest, opts ...http.CallOption) (*SeckillProductDetailResponse, error) {
	var out SeckillProductDetailResponse
	pattern := "/seckill/product/{product_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSeckillSeckillProductDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SeckillProducts 查询秒杀商品列表
func (c *SeckillHTTPClientImpl) SeckillProducts(ctx context.Context, in *SeckillProductsRequest, opts ...http.CallOption) (*SeckillProductsResponse, error) {
	var out SeckillProductsResponse
	pattern := "/seckill/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSeckillSeckillProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
