// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: seckill/v1/seckill.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Seckill_SeckillProducts_FullMethodName      = "/api.seckill.v1.Seckill/SeckillProducts"
	Seckill_SeckillProductDetail_FullMethodName = "/api.seckill.v1.Seckill/SeckillProductDetail"
	Seckill_GetCurrentActivity_FullMethodName   = "/api.seckill.v1.Seckill/GetCurrentActivity"
	Seckill_CreateSeckillOrder_FullMethodName   = "/api.seckill.v1.Seckill/CreateSeckillOrder"
	Seckill_GetSeckillOrder_FullMethodName      = "/api.seckill.v1.Seckill/GetSeckillOrder"
	Seckill_GetSeckillResult_FullMethodName     = "/api.seckill.v1.Seckill/GetSeckillResult"
	Seckill_PaySeckillOrder_FullMethodName      = "/api.seckill.v1.Seckill/PaySeckillOrder"
)

// SeckillClient is the client API for Seckill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillClient interface {
	// 查询秒杀商品列表
	SeckillProducts(ctx context.Context, in *SeckillProductsRequest, opts ...grpc.CallOption) (*SeckillProductsResponse, error)
	// 查询秒杀商品详情
	SeckillProductDetail(ctx context.Context, in *SeckillProductDetailRequest, opts ...grpc.CallOption) (*SeckillProductDetailResponse, error)
	// 秒杀活动信息
	GetCurrentActivity(ctx context.Context, in *GetCurrentActivityRequest, opts ...grpc.CallOption) (*GetCurrentActivityResponse, error)
	// 秒杀下单（核心高并发接口）
	CreateSeckillOrder(ctx context.Context, in *CreateSeckillOrderRequest, opts ...grpc.CallOption) (*CreateSeckillOrderResponse, error)
	// 查询秒杀订单
	GetSeckillOrder(ctx context.Context, in *GetSeckillOrderRequest, opts ...grpc.CallOption) (*GetSeckillOrderResponse, error)
	// 查询秒杀结果
	GetSeckillResult(ctx context.Context, in *GetSeckillResultRequest, opts ...grpc.CallOption) (*GetSeckillResultResponse, error)
	// 支付秒杀订单
	PaySeckillOrder(ctx context.Context, in *PaySeckillOrderRequest, opts ...grpc.CallOption) (*PaySeckillOrderResponse, error)
}

type seckillClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillClient(cc grpc.ClientConnInterface) SeckillClient {
	return &seckillClient{cc}
}

func (c *seckillClient) SeckillProducts(ctx context.Context, in *SeckillProductsRequest, opts ...grpc.CallOption) (*SeckillProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillProductsResponse)
	err := c.cc.Invoke(ctx, Seckill_SeckillProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) SeckillProductDetail(ctx context.Context, in *SeckillProductDetailRequest, opts ...grpc.CallOption) (*SeckillProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillProductDetailResponse)
	err := c.cc.Invoke(ctx, Seckill_SeckillProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) GetCurrentActivity(ctx context.Context, in *GetCurrentActivityRequest, opts ...grpc.CallOption) (*GetCurrentActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentActivityResponse)
	err := c.cc.Invoke(ctx, Seckill_GetCurrentActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) CreateSeckillOrder(ctx context.Context, in *CreateSeckillOrderRequest, opts ...grpc.CallOption) (*CreateSeckillOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSeckillOrderResponse)
	err := c.cc.Invoke(ctx, Seckill_CreateSeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) GetSeckillOrder(ctx context.Context, in *GetSeckillOrderRequest, opts ...grpc.CallOption) (*GetSeckillOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeckillOrderResponse)
	err := c.cc.Invoke(ctx, Seckill_GetSeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) GetSeckillResult(ctx context.Context, in *GetSeckillResultRequest, opts ...grpc.CallOption) (*GetSeckillResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeckillResultResponse)
	err := c.cc.Invoke(ctx, Seckill_GetSeckillResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) PaySeckillOrder(ctx context.Context, in *PaySeckillOrderRequest, opts ...grpc.CallOption) (*PaySeckillOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaySeckillOrderResponse)
	err := c.cc.Invoke(ctx, Seckill_PaySeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServer is the server API for Seckill service.
// All implementations must embed UnimplementedSeckillServer
// for forward compatibility.
type SeckillServer interface {
	// 查询秒杀商品列表
	SeckillProducts(context.Context, *SeckillProductsRequest) (*SeckillProductsResponse, error)
	// 查询秒杀商品详情
	SeckillProductDetail(context.Context, *SeckillProductDetailRequest) (*SeckillProductDetailResponse, error)
	// 秒杀活动信息
	GetCurrentActivity(context.Context, *GetCurrentActivityRequest) (*GetCurrentActivityResponse, error)
	// 秒杀下单（核心高并发接口）
	CreateSeckillOrder(context.Context, *CreateSeckillOrderRequest) (*CreateSeckillOrderResponse, error)
	// 查询秒杀订单
	GetSeckillOrder(context.Context, *GetSeckillOrderRequest) (*GetSeckillOrderResponse, error)
	// 查询秒杀结果
	GetSeckillResult(context.Context, *GetSeckillResultRequest) (*GetSeckillResultResponse, error)
	// 支付秒杀订单
	PaySeckillOrder(context.Context, *PaySeckillOrderRequest) (*PaySeckillOrderResponse, error)
	mustEmbedUnimplementedSeckillServer()
}

// UnimplementedSeckillServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeckillServer struct{}

func (UnimplementedSeckillServer) SeckillProducts(context.Context, *SeckillProductsRequest) (*SeckillProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeckillProducts not implemented")
}
func (UnimplementedSeckillServer) SeckillProductDetail(context.Context, *SeckillProductDetailRequest) (*SeckillProductDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeckillProductDetail not implemented")
}
func (UnimplementedSeckillServer) GetCurrentActivity(context.Context, *GetCurrentActivityRequest) (*GetCurrentActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentActivity not implemented")
}
func (UnimplementedSeckillServer) CreateSeckillOrder(context.Context, *CreateSeckillOrderRequest) (*CreateSeckillOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeckillOrder not implemented")
}
func (UnimplementedSeckillServer) GetSeckillOrder(context.Context, *GetSeckillOrderRequest) (*GetSeckillOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillOrder not implemented")
}
func (UnimplementedSeckillServer) GetSeckillResult(context.Context, *GetSeckillResultRequest) (*GetSeckillResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillResult not implemented")
}
func (UnimplementedSeckillServer) PaySeckillOrder(context.Context, *PaySeckillOrderRequest) (*PaySeckillOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PaySeckillOrder not implemented")
}
func (UnimplementedSeckillServer) mustEmbedUnimplementedSeckillServer() {}
func (UnimplementedSeckillServer) testEmbeddedByValue()                 {}

// UnsafeSeckillServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillServer will
// result in compilation errors.
type UnsafeSeckillServer interface {
	mustEmbedUnimplementedSeckillServer()
}

func RegisterSeckillServer(s grpc.ServiceRegistrar, srv SeckillServer) {
	// If the following call panics, it indicates UnimplementedSeckillServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Seckill_ServiceDesc, srv)
}

func _Seckill_SeckillProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).SeckillProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_SeckillProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).SeckillProducts(ctx, req.(*SeckillProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_SeckillProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).SeckillProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_SeckillProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).SeckillProductDetail(ctx, req.(*SeckillProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_GetCurrentActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).GetCurrentActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_GetCurrentActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).GetCurrentActivity(ctx, req.(*GetCurrentActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_CreateSeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeckillOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).CreateSeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_CreateSeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).CreateSeckillOrder(ctx, req.(*CreateSeckillOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_GetSeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).GetSeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_GetSeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).GetSeckillOrder(ctx, req.(*GetSeckillOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_GetSeckillResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).GetSeckillResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_GetSeckillResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).GetSeckillResult(ctx, req.(*GetSeckillResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_PaySeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaySeckillOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).PaySeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_PaySeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).PaySeckillOrder(ctx, req.(*PaySeckillOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Seckill_ServiceDesc is the grpc.ServiceDesc for Seckill service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seckill_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.seckill.v1.Seckill",
	HandlerType: (*SeckillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeckillProducts",
			Handler:    _Seckill_SeckillProducts_Handler,
		},
		{
			MethodName: "SeckillProductDetail",
			Handler:    _Seckill_SeckillProductDetail_Handler,
		},
		{
			MethodName: "GetCurrentActivity",
			Handler:    _Seckill_GetCurrentActivity_Handler,
		},
		{
			MethodName: "CreateSeckillOrder",
			Handler:    _Seckill_CreateSeckillOrder_Handler,
		},
		{
			MethodName: "GetSeckillOrder",
			Handler:    _Seckill_GetSeckillOrder_Handler,
		},
		{
			MethodName: "GetSeckillResult",
			Handler:    _Seckill_GetSeckillResult_Handler,
		},
		{
			MethodName: "PaySeckillOrder",
			Handler:    _Seckill_PaySeckillOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seckill/v1/seckill.proto",
}
