// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: seckill/v1/seckill.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//	------------1.秒杀商品浏览------------
//
// 查询秒杀商品列表
type SeckillProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动ID，不传则获取当前进行中的活动
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortType      int32                  `protobuf:"varint,5,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"` // 排序：1-默认 2-价格升序 3-价格降序 4-库存升序 5-销量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillProductsRequest) Reset() {
	*x = SeckillProductsRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProductsRequest) ProtoMessage() {}

func (x *SeckillProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProductsRequest.ProtoReflect.Descriptor instead.
func (*SeckillProductsRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillProductsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillProductsRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *SeckillProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SeckillProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SeckillProductsRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type SeckillProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Activity      *ActivityInfo          `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"` //活动概要
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillProductsResponse) Reset() {
	*x = SeckillProductsResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProductsResponse) ProtoMessage() {}

func (x *SeckillProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProductsResponse.ProtoReflect.Descriptor instead.
func (*SeckillProductsResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillProductsResponse) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SeckillProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SeckillProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SeckillProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SeckillProductsResponse) GetActivity() *ActivityInfo {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ProductInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkuId          int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // seckill_sku.id
	ProductId      int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MainImage      string                 `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	SeckillPrice   int64                  `protobuf:"varint,5,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	MarketPrice    int64                  `protobuf:"varint,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	AvailableStock int64                  `protobuf:"varint,7,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	TotalStock     int64                  `protobuf:"varint,8,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	LimitNum       int64                  `protobuf:"varint,9,opt,name=limit_num,json=limitNum,proto3" json:"limit_num,omitempty"`
	SaleRate       int64                  `protobuf:"varint,10,opt,name=sale_rate,json=saleRate,proto3" json:"sale_rate,omitempty"`                  // 销售进度
	UserHasBought  bool                   `protobuf:"varint,11,opt,name=user_has_bought,json=userHasBought,proto3" json:"user_has_bought,omitempty"` //是否已经购买
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *ProductInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ProductInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductInfo) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *ProductInfo) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *ProductInfo) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *ProductInfo) GetTotalStock() int64 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *ProductInfo) GetLimitNum() int64 {
	if x != nil {
		return x.LimitNum
	}
	return 0
}

func (x *ProductInfo) GetSaleRate() int64 {
	if x != nil {
		return x.SaleRate
	}
	return 0
}

func (x *ProductInfo) GetUserHasBought() bool {
	if x != nil {
		return x.UserHasBought
	}
	return false
}

// 秒杀商品详情
type SeckillProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillProductDetailRequest) Reset() {
	*x = SeckillProductDetailRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProductDetailRequest) ProtoMessage() {}

func (x *SeckillProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProductDetailRequest.ProtoReflect.Descriptor instead.
func (*SeckillProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *SeckillProductDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillProductDetailRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillProductDetailRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type SeckillProductDetailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Product          *ProductDetail         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	AvailableCoupons []*CouponInfo          `protobuf:"bytes,2,rep,name=available_coupons,json=availableCoupons,proto3" json:"available_coupons,omitempty"` // 可用优惠券
	UserStatus       *UserSeckillStatus     `protobuf:"bytes,3,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`                   // 用户秒杀状态
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeckillProductDetailResponse) Reset() {
	*x = SeckillProductDetailResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProductDetailResponse) ProtoMessage() {}

func (x *SeckillProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProductDetailResponse.ProtoReflect.Descriptor instead.
func (*SeckillProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *SeckillProductDetailResponse) GetProduct() *ProductDetail {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *SeckillProductDetailResponse) GetAvailableCoupons() []*CouponInfo {
	if x != nil {
		return x.AvailableCoupons
	}
	return nil
}

func (x *SeckillProductDetailResponse) GetUserStatus() *UserSeckillStatus {
	if x != nil {
		return x.UserStatus
	}
	return nil
}

type ProductDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品基础信息（Product）
	ProductId int64  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle  string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	MainImage string `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Detail    string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	// 秒杀信息（seckill_sku)
	SkuId          int64 `protobuf:"varint,6,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SeckillPrice   int64 `protobuf:"varint,7,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	MarketPrice    int64 `protobuf:"varint,8,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	TotalStock     int64 `protobuf:"varint,9,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	AvailableStock int64 `protobuf:"varint,10,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	LimitNum       int64 `protobuf:"varint,11,opt,name=limit_num,json=limitNum,proto3" json:"limit_num,omitempty"` // 限买数量
	// 活动信息(seckill_activity)
	ActivityId          int64  `protobuf:"varint,12,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityTitle       string `protobuf:"bytes,13,opt,name=activity_title,json=activityTitle,proto3" json:"activity_title,omitempty"`
	ActivityDescription string `protobuf:"bytes,14,opt,name=activity_description,json=activityDescription,proto3" json:"activity_description,omitempty"`
	StartTime           string `protobuf:"bytes,15,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             string `protobuf:"bytes,16,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ActivityStatus      int64  `protobuf:"varint,17,opt,name=activity_status,json=activityStatus,proto3" json:"activity_status,omitempty"`       // 0-未开始 1-进行中 2-已结束
	RemainingSeconds    int64  `protobuf:"varint,18,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"` // 倒计时
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *ProductDetail) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetail) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ProductDetail) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductDetail) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProductDetail) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ProductDetail) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *ProductDetail) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *ProductDetail) GetTotalStock() int64 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *ProductDetail) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *ProductDetail) GetLimitNum() int64 {
	if x != nil {
		return x.LimitNum
	}
	return 0
}

func (x *ProductDetail) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ProductDetail) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *ProductDetail) GetActivityDescription() string {
	if x != nil {
		return x.ActivityDescription
	}
	return ""
}

func (x *ProductDetail) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ProductDetail) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ProductDetail) GetActivityStatus() int64 {
	if x != nil {
		return x.ActivityStatus
	}
	return 0
}

func (x *ProductDetail) GetRemainingSeconds() int64 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

// 用户秒杀状态
type UserSeckillStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasBought      bool                   `protobuf:"varint,1,opt,name=has_bought,json=hasBought,proto3" json:"has_bought,omitempty"`
	BoughtQuantity int64                  `protobuf:"varint,2,opt,name=bought_quantity,json=boughtQuantity,proto3" json:"bought_quantity,omitempty"`
	CanBuy         bool                   `protobuf:"varint,3,opt,name=can_buy,json=canBuy,proto3" json:"can_buy,omitempty"`                         // 是否可购买（未超限购、活动进行中、有库存）
	RemainingLimit int64                  `protobuf:"varint,4,opt,name=remaining_limit,json=remainingLimit,proto3" json:"remaining_limit,omitempty"` // 剩余可购数量（limit_num - bought_quantity）
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                      //提示信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserSeckillStatus) Reset() {
	*x = UserSeckillStatus{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSeckillStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSeckillStatus) ProtoMessage() {}

func (x *UserSeckillStatus) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSeckillStatus.ProtoReflect.Descriptor instead.
func (*UserSeckillStatus) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{6}
}

func (x *UserSeckillStatus) GetHasBought() bool {
	if x != nil {
		return x.HasBought
	}
	return false
}

func (x *UserSeckillStatus) GetBoughtQuantity() int64 {
	if x != nil {
		return x.BoughtQuantity
	}
	return 0
}

func (x *UserSeckillStatus) GetCanBuy() bool {
	if x != nil {
		return x.CanBuy
	}
	return false
}

func (x *UserSeckillStatus) GetRemainingLimit() int64 {
	if x != nil {
		return x.RemainingLimit
	}
	return 0
}

func (x *UserSeckillStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 活动概要
type ActivityInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime        string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RemainingSeconds int64                  `protobuf:"varint,7,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{7}
}

func (x *ActivityInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActivityInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ActivityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityInfo) GetRemainingSeconds() int64 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

// -------------2.秒杀活动信息-------------
type GetCurrentActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentActivityRequest) Reset() {
	*x = GetCurrentActivityRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentActivityRequest) ProtoMessage() {}

func (x *GetCurrentActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentActivityRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentActivityRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{8}
}

type GetCurrentActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityInfo          `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	ProductCount  int64                  `protobuf:"varint,2,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"` // 活动商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentActivityResponse) Reset() {
	*x = GetCurrentActivityResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentActivityResponse) ProtoMessage() {}

func (x *GetCurrentActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentActivityResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentActivityResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{9}
}

func (x *GetCurrentActivityResponse) GetActivity() *ActivityInfo {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *GetCurrentActivityResponse) GetProductCount() int64 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

// ------------3.秒杀下单-----------
// 优惠券简略信息（从优惠券服务获取）
type CouponInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                            // 1-满减 2-打折
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                          // 面额或折扣率
	MinAmount     int64                  `protobuf:"varint,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"` // 使用门槛
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsUsable      bool                   `protobuf:"varint,7,opt,name=is_usable,json=isUsable,proto3" json:"is_usable,omitempty"` // 当前商品是否可用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfo) Reset() {
	*x = CouponInfo{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfo) ProtoMessage() {}

func (x *CouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfo.ProtoReflect.Descriptor instead.
func (*CouponInfo) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{10}
}

func (x *CouponInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponInfo) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CouponInfo) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CouponInfo) GetIsUsable() bool {
	if x != nil {
		return x.IsUsable
	}
	return false
}

// 创建秒杀订单（核心接口）
type CreateSeckillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // seckill_sku.id
	ActivityId    int64                  `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                 // 默认1
	CouponId      int64                  `protobuf:"varint,6,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 使用的优惠券ID（可选）
	AddressId     int64                  `protobuf:"varint,7,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`    // 用于限流
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 幂等请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillOrderRequest) Reset() {
	*x = CreateSeckillOrderRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillOrderRequest) ProtoMessage() {}

func (x *CreateSeckillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSeckillOrderRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSeckillOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreateSeckillOrderRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CreateSeckillOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateSeckillOrderResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderNo          string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OrderAmount      int64                  `protobuf:"varint,2,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`                // 订单原总金额
	CouponDiscount   int64                  `protobuf:"varint,3,opt,name=coupon_discount,json=couponDiscount,proto3" json:"coupon_discount,omitempty"`       // 优惠券抵扣
	FinalAmount      int64                  `protobuf:"varint,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`                // 实付金额
	Status           int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                             // 0-待支付 1-已支付
	SeckillPrice     int64                  `protobuf:"varint,6,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`             // 秒杀单价
	Quantity         int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`                                         // 购买数量
	Message          string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`                                            // 提示信息
	RemainingSeconds int64                  `protobuf:"varint,9,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"` //  支付倒计时
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSeckillOrderResponse) Reset() {
	*x = CreateSeckillOrderResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillOrderResponse) ProtoMessage() {}

func (x *CreateSeckillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateSeckillOrderResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSeckillOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateSeckillOrderResponse) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetCouponDiscount() int64 {
	if x != nil {
		return x.CouponDiscount
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateSeckillOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSeckillOrderResponse) GetRemainingSeconds() int64 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

// ---------------4.秒杀订单查询---------------
// 查询秒杀订单
type GetSeckillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用于鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillOrderRequest) Reset() {
	*x = GetSeckillOrderRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillOrderRequest) ProtoMessage() {}

func (x *GetSeckillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillOrderRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillOrderRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{13}
}

func (x *GetSeckillOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetSeckillOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSeckillOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *SeckillOrderInfo      `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillOrderResponse) Reset() {
	*x = GetSeckillOrderResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillOrderResponse) ProtoMessage() {}

func (x *GetSeckillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillOrderResponse.ProtoReflect.Descriptor instead.
func (*GetSeckillOrderResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{14}
}

func (x *GetSeckillOrderResponse) GetOrder() *SeckillOrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

// 秒杀订单信息
type SeckillOrderInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderNo          string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId       int64                  `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId        int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId            int64                  `protobuf:"varint,5,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductName      string                 `protobuf:"bytes,6,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage     string                 `protobuf:"bytes,7,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	SeckillPrice     int64                  `protobuf:"varint,8,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	Quantity         int64                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderAmount      int64                  `protobuf:"varint,10,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	CouponId         int64                  `protobuf:"varint,11,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	CouponDiscount   int64                  `protobuf:"varint,12,opt,name=coupon_discount,json=couponDiscount,proto3" json:"coupon_discount,omitempty"`
	FinalAmount      int64                  `protobuf:"varint,13,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Status           int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"` // 0-待支付 1-已支付 2-已取消 3-已退款
	CreateTime       string                 `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PayTime          string                 `protobuf:"bytes,16,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	Address          *AddressSnapshot       `protobuf:"bytes,17,opt,name=address,proto3" json:"address,omitempty"`
	RemainingSeconds int64                  `protobuf:"varint,18,opt,name=Remaining_seconds,json=RemainingSeconds,proto3" json:"Remaining_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeckillOrderInfo) Reset() {
	*x = SeckillOrderInfo{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderInfo) ProtoMessage() {}

func (x *SeckillOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderInfo.ProtoReflect.Descriptor instead.
func (*SeckillOrderInfo) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{15}
}

func (x *SeckillOrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SeckillOrderInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillOrderInfo) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *SeckillOrderInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillOrderInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SeckillOrderInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SeckillOrderInfo) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *SeckillOrderInfo) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *SeckillOrderInfo) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SeckillOrderInfo) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *SeckillOrderInfo) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *SeckillOrderInfo) GetCouponDiscount() int64 {
	if x != nil {
		return x.CouponDiscount
	}
	return 0
}

func (x *SeckillOrderInfo) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *SeckillOrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SeckillOrderInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SeckillOrderInfo) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *SeckillOrderInfo) GetAddress() *AddressSnapshot {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SeckillOrderInfo) GetRemainingSeconds() int64 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

// 收货地址
type AddressSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,2,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone string                 `protobuf:"bytes,3,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddress string                 `protobuf:"bytes,7,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressSnapshot) Reset() {
	*x = AddressSnapshot{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSnapshot) ProtoMessage() {}

func (x *AddressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSnapshot.ProtoReflect.Descriptor instead.
func (*AddressSnapshot) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{16}
}

func (x *AddressSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressSnapshot) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *AddressSnapshot) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *AddressSnapshot) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressSnapshot) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressSnapshot) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressSnapshot) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

// ------------------5.秒杀结果查询------------------
type GetSeckillResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 创建订单时的请求ID
	ActivityId    int64                  `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillResultRequest) Reset() {
	*x = GetSeckillResultRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillResultRequest) ProtoMessage() {}

func (x *GetSeckillResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillResultRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillResultRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{17}
}

func (x *GetSeckillResultRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSeckillResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetSeckillResultRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetSeckillResultRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetSeckillResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                              // 0-处理中 1-成功 2-失败
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`              // 返回的订单号
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                             // 失败原因
	OrderAmount   int64                  `protobuf:"varint,4,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"` //成功是返回实付金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillResultResponse) Reset() {
	*x = GetSeckillResultResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillResultResponse) ProtoMessage() {}

func (x *GetSeckillResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillResultResponse.ProtoReflect.Descriptor instead.
func (*GetSeckillResultResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{18}
}

func (x *GetSeckillResultResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetSeckillResultResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetSeckillResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSeckillResultResponse) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

// 支付订单
type PaySeckillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayPlatform   int32                  `protobuf:"varint,3,opt,name=pay_platform,json=payPlatform,proto3" json:"pay_platform,omitempty"` // 1-支付宝 2-微信
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaySeckillOrderRequest) Reset() {
	*x = PaySeckillOrderRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaySeckillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySeckillOrderRequest) ProtoMessage() {}

func (x *PaySeckillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySeckillOrderRequest.ProtoReflect.Descriptor instead.
func (*PaySeckillOrderRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{19}
}

func (x *PaySeckillOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaySeckillOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaySeckillOrderRequest) GetPayPlatform() int32 {
	if x != nil {
		return x.PayPlatform
	}
	return 0
}

type PaySeckillOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayUrl         string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"` //支付链接
	PayAmount      int64                  `protobuf:"varint,4,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	PlatformNumber string                 `protobuf:"bytes,5,opt,name=platform_number,json=platformNumber,proto3" json:"platform_number,omitempty"` //支付平台流水号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaySeckillOrderResponse) Reset() {
	*x = PaySeckillOrderResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaySeckillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySeckillOrderResponse) ProtoMessage() {}

func (x *PaySeckillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySeckillOrderResponse.ProtoReflect.Descriptor instead.
func (*PaySeckillOrderResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{20}
}

func (x *PaySeckillOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaySeckillOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaySeckillOrderResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *PaySeckillOrderResponse) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *PaySeckillOrderResponse) GetPlatformNumber() string {
	if x != nil {
		return x.PlatformNumber
	}
	return ""
}

var File_seckill_v1_seckill_proto protoreflect.FileDescriptor

const file_seckill_v1_seckill_proto_rawDesc = "" +
	"\n" +
	"\x18seckill/v1/seckill.proto\x12\x0eapi.seckill.v1\"\xa0\x01\n" +
	"\x16SeckillProductsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tsort_type\x18\x05 \x01(\x05R\bsortType\"\xd3\x01\n" +
	"\x17SeckillProductsResponse\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.api.seckill.v1.ProductInfoR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x128\n" +
	"\bactivity\x18\x05 \x01(\v2\x1c.api.seckill.v1.ActivityInfoR\bactivity\"\xea\x02\n" +
	"\vProductInfo\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x04 \x01(\tR\tmainImage\x12#\n" +
	"\rseckill_price\x18\x05 \x01(\x03R\fseckillPrice\x12!\n" +
	"\fmarket_price\x18\x06 \x01(\x03R\vmarketPrice\x12'\n" +
	"\x0favailable_stock\x18\a \x01(\x03R\x0eavailableStock\x12\x1f\n" +
	"\vtotal_stock\x18\b \x01(\x03R\n" +
	"totalStock\x12\x1b\n" +
	"\tlimit_num\x18\t \x01(\x03R\blimitNum\x12\x1b\n" +
	"\tsale_rate\x18\n" +
	" \x01(\x03R\bsaleRate\x12&\n" +
	"\x0fuser_has_bought\x18\v \x01(\bR\ruserHasBought\"v\n" +
	"\x1bSeckillProductDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\"\xe4\x01\n" +
	"\x1cSeckillProductDetailResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.api.seckill.v1.ProductDetailR\aproduct\x12G\n" +
	"\x11available_coupons\x18\x02 \x03(\v2\x1a.api.seckill.v1.CouponInfoR\x10availableCoupons\x12B\n" +
	"\vuser_status\x18\x03 \x01(\v2!.api.seckill.v1.UserSeckillStatusR\n" +
	"userStatus\"\xe6\x04\n" +
	"\rProductDetail\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x1d\n" +
	"\n" +
	"main_image\x18\x04 \x01(\tR\tmainImage\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x15\n" +
	"\x06sku_id\x18\x06 \x01(\x03R\x05skuId\x12#\n" +
	"\rseckill_price\x18\a \x01(\x03R\fseckillPrice\x12!\n" +
	"\fmarket_price\x18\b \x01(\x03R\vmarketPrice\x12\x1f\n" +
	"\vtotal_stock\x18\t \x01(\x03R\n" +
	"totalStock\x12'\n" +
	"\x0favailable_stock\x18\n" +
	" \x01(\x03R\x0eavailableStock\x12\x1b\n" +
	"\tlimit_num\x18\v \x01(\x03R\blimitNum\x12\x1f\n" +
	"\vactivity_id\x18\f \x01(\x03R\n" +
	"activityId\x12%\n" +
	"\x0eactivity_title\x18\r \x01(\tR\ractivityTitle\x121\n" +
	"\x14activity_description\x18\x0e \x01(\tR\x13activityDescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x0f \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x10 \x01(\tR\aendTime\x12'\n" +
	"\x0factivity_status\x18\x11 \x01(\x03R\x0eactivityStatus\x12+\n" +
	"\x11remaining_seconds\x18\x12 \x01(\x03R\x10remainingSeconds\"\xb7\x01\n" +
	"\x11UserSeckillStatus\x12\x1d\n" +
	"\n" +
	"has_bought\x18\x01 \x01(\bR\thasBought\x12'\n" +
	"\x0fbought_quantity\x18\x02 \x01(\x03R\x0eboughtQuantity\x12\x17\n" +
	"\acan_buy\x18\x03 \x01(\bR\x06canBuy\x12'\n" +
	"\x0fremaining_limit\x18\x04 \x01(\x03R\x0eremainingLimit\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xd5\x01\n" +
	"\fActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12+\n" +
	"\x11remaining_seconds\x18\a \x01(\x03R\x10remainingSeconds\"\x1b\n" +
	"\x19GetCurrentActivityRequest\"{\n" +
	"\x1aGetCurrentActivityResponse\x128\n" +
	"\bactivity\x18\x01 \x01(\v2\x1c.api.seckill.v1.ActivityInfoR\bactivity\x12#\n" +
	"\rproduct_count\x18\x02 \x01(\x03R\fproductCount\"\xb1\x01\n" +
	"\n" +
	"CouponInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x03R\tminAmount\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_usable\x18\a \x01(\bR\bisUsable\"\x9f\x02\n" +
	"\x19CreateSeckillOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x05skuId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1b\n" +
	"\tcoupon_id\x18\x06 \x01(\x03R\bcouponId\x12\x1d\n" +
	"\n" +
	"address_id\x18\a \x01(\x03R\taddressId\x12\x1b\n" +
	"\tclient_ip\x18\b \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\"\xc6\x02\n" +
	"\x1aCreateSeckillOrderResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12!\n" +
	"\forder_amount\x18\x02 \x01(\x03R\vorderAmount\x12'\n" +
	"\x0fcoupon_discount\x18\x03 \x01(\x03R\x0ecouponDiscount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x03R\vfinalAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12#\n" +
	"\rseckill_price\x18\x06 \x01(\x03R\fseckillPrice\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12+\n" +
	"\x11remaining_seconds\x18\t \x01(\x03R\x10remainingSeconds\"L\n" +
	"\x16GetSeckillOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"Q\n" +
	"\x17GetSeckillOrderResponse\x126\n" +
	"\x05order\x18\x01 \x01(\v2 .api.seckill.v1.SeckillOrderInfoR\x05order\"\xee\x04\n" +
	"\x10SeckillOrderInfo\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x05 \x01(\x03R\x05skuId\x12!\n" +
	"\fproduct_name\x18\x06 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\a \x01(\tR\fproductImage\x12#\n" +
	"\rseckill_price\x18\b \x01(\x03R\fseckillPrice\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x03R\bquantity\x12!\n" +
	"\forder_amount\x18\n" +
	" \x01(\x03R\vorderAmount\x12\x1b\n" +
	"\tcoupon_id\x18\v \x01(\x03R\bcouponId\x12'\n" +
	"\x0fcoupon_discount\x18\f \x01(\x03R\x0ecouponDiscount\x12!\n" +
	"\ffinal_amount\x18\r \x01(\x03R\vfinalAmount\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x0f \x01(\tR\n" +
	"createTime\x12\x19\n" +
	"\bpay_time\x18\x10 \x01(\tR\apayTime\x129\n" +
	"\aaddress\x18\x11 \x01(\v2\x1f.api.seckill.v1.AddressSnapshotR\aaddress\x12+\n" +
	"\x11Remaining_seconds\x18\x12 \x01(\x03R\x10RemainingSeconds\"\xe0\x01\n" +
	"\x0fAddressSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rreceiver_name\x18\x02 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x03 \x01(\tR\rreceiverPhone\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12%\n" +
	"\x0edetail_address\x18\a \x01(\tR\rdetailAddress\"\x91\x01\n" +
	"\x17GetSeckillResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\"\x8a\x01\n" +
	"\x18GetSeckillResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\forder_amount\x18\x04 \x01(\x03R\vorderAmount\"o\n" +
	"\x16PaySeckillOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fpay_platform\x18\x03 \x01(\x05R\vpayPlatform\"\xae\x01\n" +
	"\x17PaySeckillOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x04 \x01(\x03R\tpayAmount\x12'\n" +
	"\x0fplatform_number\x18\x05 \x01(\tR\x0eplatformNumber2\xf7\x05\n" +
	"\aSeckill\x12d\n" +
	"\x0fSeckillProducts\x12&.api.seckill.v1.SeckillProductsRequest\x1a'.api.seckill.v1.SeckillProductsResponse\"\x00\x12s\n" +
	"\x14SeckillProductDetail\x12+.api.seckill.v1.SeckillProductDetailRequest\x1a,.api.seckill.v1.SeckillProductDetailResponse\"\x00\x12m\n" +
	"\x12GetCurrentActivity\x12).api.seckill.v1.GetCurrentActivityRequest\x1a*.api.seckill.v1.GetCurrentActivityResponse\"\x00\x12m\n" +
	"\x12CreateSeckillOrder\x12).api.seckill.v1.CreateSeckillOrderRequest\x1a*.api.seckill.v1.CreateSeckillOrderResponse\"\x00\x12d\n" +
	"\x0fGetSeckillOrder\x12&.api.seckill.v1.GetSeckillOrderRequest\x1a'.api.seckill.v1.GetSeckillOrderResponse\"\x00\x12g\n" +
	"\x10GetSeckillResult\x12'.api.seckill.v1.GetSeckillResultRequest\x1a(.api.seckill.v1.GetSeckillResultResponse\"\x00\x12d\n" +
	"\x0fPaySeckillOrder\x12&.api.seckill.v1.PaySeckillOrderRequest\x1a'.api.seckill.v1.PaySeckillOrderResponse\"\x00B5\n" +
	"\x0eapi.seckill.v1P\x01Z!seckill-service/api/seckill/v1;v1b\x06proto3"

var (
	file_seckill_v1_seckill_proto_rawDescOnce sync.Once
	file_seckill_v1_seckill_proto_rawDescData []byte
)

func file_seckill_v1_seckill_proto_rawDescGZIP() []byte {
	file_seckill_v1_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_v1_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)))
	})
	return file_seckill_v1_seckill_proto_rawDescData
}

var file_seckill_v1_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_seckill_v1_seckill_proto_goTypes = []any{
	(*SeckillProductsRequest)(nil),       // 0: api.seckill.v1.SeckillProductsRequest
	(*SeckillProductsResponse)(nil),      // 1: api.seckill.v1.SeckillProductsResponse
	(*ProductInfo)(nil),                  // 2: api.seckill.v1.ProductInfo
	(*SeckillProductDetailRequest)(nil),  // 3: api.seckill.v1.SeckillProductDetailRequest
	(*SeckillProductDetailResponse)(nil), // 4: api.seckill.v1.SeckillProductDetailResponse
	(*ProductDetail)(nil),                // 5: api.seckill.v1.ProductDetail
	(*UserSeckillStatus)(nil),            // 6: api.seckill.v1.UserSeckillStatus
	(*ActivityInfo)(nil),                 // 7: api.seckill.v1.ActivityInfo
	(*GetCurrentActivityRequest)(nil),    // 8: api.seckill.v1.GetCurrentActivityRequest
	(*GetCurrentActivityResponse)(nil),   // 9: api.seckill.v1.GetCurrentActivityResponse
	(*CouponInfo)(nil),                   // 10: api.seckill.v1.CouponInfo
	(*CreateSeckillOrderRequest)(nil),    // 11: api.seckill.v1.CreateSeckillOrderRequest
	(*CreateSeckillOrderResponse)(nil),   // 12: api.seckill.v1.CreateSeckillOrderResponse
	(*GetSeckillOrderRequest)(nil),       // 13: api.seckill.v1.GetSeckillOrderRequest
	(*GetSeckillOrderResponse)(nil),      // 14: api.seckill.v1.GetSeckillOrderResponse
	(*SeckillOrderInfo)(nil),             // 15: api.seckill.v1.SeckillOrderInfo
	(*AddressSnapshot)(nil),              // 16: api.seckill.v1.AddressSnapshot
	(*GetSeckillResultRequest)(nil),      // 17: api.seckill.v1.GetSeckillResultRequest
	(*GetSeckillResultResponse)(nil),     // 18: api.seckill.v1.GetSeckillResultResponse
	(*PaySeckillOrderRequest)(nil),       // 19: api.seckill.v1.PaySeckillOrderRequest
	(*PaySeckillOrderResponse)(nil),      // 20: api.seckill.v1.PaySeckillOrderResponse
}
var file_seckill_v1_seckill_proto_depIdxs = []int32{
	2,  // 0: api.seckill.v1.SeckillProductsResponse.products:type_name -> api.seckill.v1.ProductInfo
	7,  // 1: api.seckill.v1.SeckillProductsResponse.activity:type_name -> api.seckill.v1.ActivityInfo
	5,  // 2: api.seckill.v1.SeckillProductDetailResponse.product:type_name -> api.seckill.v1.ProductDetail
	10, // 3: api.seckill.v1.SeckillProductDetailResponse.available_coupons:type_name -> api.seckill.v1.CouponInfo
	6,  // 4: api.seckill.v1.SeckillProductDetailResponse.user_status:type_name -> api.seckill.v1.UserSeckillStatus
	7,  // 5: api.seckill.v1.GetCurrentActivityResponse.activity:type_name -> api.seckill.v1.ActivityInfo
	15, // 6: api.seckill.v1.GetSeckillOrderResponse.order:type_name -> api.seckill.v1.SeckillOrderInfo
	16, // 7: api.seckill.v1.SeckillOrderInfo.address:type_name -> api.seckill.v1.AddressSnapshot
	0,  // 8: api.seckill.v1.Seckill.SeckillProducts:input_type -> api.seckill.v1.SeckillProductsRequest
	3,  // 9: api.seckill.v1.Seckill.SeckillProductDetail:input_type -> api.seckill.v1.SeckillProductDetailRequest
	8,  // 10: api.seckill.v1.Seckill.GetCurrentActivity:input_type -> api.seckill.v1.GetCurrentActivityRequest
	11, // 11: api.seckill.v1.Seckill.CreateSeckillOrder:input_type -> api.seckill.v1.CreateSeckillOrderRequest
	13, // 12: api.seckill.v1.Seckill.GetSeckillOrder:input_type -> api.seckill.v1.GetSeckillOrderRequest
	17, // 13: api.seckill.v1.Seckill.GetSeckillResult:input_type -> api.seckill.v1.GetSeckillResultRequest
	19, // 14: api.seckill.v1.Seckill.PaySeckillOrder:input_type -> api.seckill.v1.PaySeckillOrderRequest
	1,  // 15: api.seckill.v1.Seckill.SeckillProducts:output_type -> api.seckill.v1.SeckillProductsResponse
	4,  // 16: api.seckill.v1.Seckill.SeckillProductDetail:output_type -> api.seckill.v1.SeckillProductDetailResponse
	9,  // 17: api.seckill.v1.Seckill.GetCurrentActivity:output_type -> api.seckill.v1.GetCurrentActivityResponse
	12, // 18: api.seckill.v1.Seckill.CreateSeckillOrder:output_type -> api.seckill.v1.CreateSeckillOrderResponse
	14, // 19: api.seckill.v1.Seckill.GetSeckillOrder:output_type -> api.seckill.v1.GetSeckillOrderResponse
	18, // 20: api.seckill.v1.Seckill.GetSeckillResult:output_type -> api.seckill.v1.GetSeckillResultResponse
	20, // 21: api.seckill.v1.Seckill.PaySeckillOrder:output_type -> api.seckill.v1.PaySeckillOrderResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_seckill_v1_seckill_proto_init() }
func file_seckill_v1_seckill_proto_init() {
	if File_seckill_v1_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_v1_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_v1_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_v1_seckill_proto_msgTypes,
	}.Build()
	File_seckill_v1_seckill_proto = out.File
	file_seckill_v1_seckill_proto_goTypes = nil
	file_seckill_v1_seckill_proto_depIdxs = nil
}
